name: Deploy EC2
on:
  push:
    branches: [master]
jobs:
   job_one:
     name: Deploy
     runs-on: ubuntu-latest
     steps:
       - name: server ssh connection
         uses: shimataro/ssh-key-action@v2
         with:
           known_hosts: 18.191.89.200
           username: ubuntu
           key: ${{ secrets.AIRFLOW }}
           port: 22
           script: |
              rm -fr airflow-datalake-dags
