name: Deploy EC2
on:
  push:
    branches:
      - main
 jobs:
   job_one:
     name: Deploy
     runs-on: ubuntu-latest
     steps:
       - name: server ssh connection
         uses: appleboy/ssh-action@master
         with:
           host: 18.191.89.200
           username: ubuntu
           key: {{ secrets.AIRFLOW_SECRET }}
           port: 22
           script:
              cd airflow-datalake-dags
              git pull
              git status