name: Deploy EC2
on:
  push:
    branches: [main]
jobs:
   job_one:
     name: Deploy
     runs-on: ubuntu-latest
     steps:
       - name: server ssh connection
         uses: shimataro/ssh-key-action@v2
         with:
           known_hosts: 18.191.89.200
           username: ubuntu
           port: 22
           key: ${{ secrets.AIRFLOW }}
           script: |
              git clone https://github.com/michelmiranda/airflow-datalake-dags.git
